"use client";

import { useEffect, useEffectEvent, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BookOpen, Captions, Download, FileText, Loader2, RefreshCw, Sparkles, Video } from "lucide-react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

type Project = { id: string; name: string; source_type: string; source_url?: string | null; original_filename?: string | null; status: string; processing_progress: number; processing_step: string; error_message?: string | null; duration?: number | null; width?: number | null; height?: number | null; thumbnail_path?: string | null; video_file_path?: string | null; audio_path?: string | null };
type Segment = { start: number; end: number; text: string };
type Short = { id: string; title: string; start: number; duration: number; hook?: string | null; status: string; video_url?: string | null };
type Chapter = { id: number; start_time: number; title: string };
type Package = { title_suggestions: string[]; description: string; hashtags: string[]; tags: string[]; hooks: string[]; thumbnail_text_suggestions: string[]; status: string; error_message?: string | null };
type Caption = { project_id: string; status: string; language: string; segment_count: number; srt: string; vtt: string };

function time(seconds: number) { const total = Math.max(0, Math.floor(seconds || 0)); return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`; }
function errorMessage(value: unknown) { return value instanceof Error ? value.message : "Request failed"; }
function thumbnailErrorMessage(value: unknown) { const message = errorMessage(value); if (message.includes("Gemini AI is not configured")) return "Gemini is not configured. Add your Gemini API key in the backend environment settings."; if (message.includes("No Gemini image-generation model")) return "No Gemini image-generation model is configured. Configure GEMINI_IMAGE_MODEL first."; return "Thumbnail generation failed. Please try again."; }

export default function ProjectDetail({ params }: { params: Promise<{ projectId: string }> }) {
  const [projectId, setProjectId] = useState("");
  const [project, setProject] = useState<Project | null>(null);
  const [transcript, setTranscript] = useState<{ text: string; status: string; segments: Segment[] } | null>(null);
  const [shorts, setShorts] = useState<Short[]>([]);
  const [chapters, setChapters] = useState<Chapter[]>([]);
  const [contentPackage, setContentPackage] = useState<Package | null>(null);
  const [caption, setCaption] = useState<Caption | null>(null);
  const [thumbnailPrompt, setThumbnailPrompt] = useState("");
  const [thumbnailUrl, setThumbnailUrl] = useState<string | null>(null);
  const [thumbnailError, setThumbnailError] = useState("");
  const [thumbnailBusy, setThumbnailBusy] = useState(false);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");

  async function request(path: string, options?: RequestInit) { const response = await fetch(`${API}${path}`, options); if (!response.ok) { const body = await response.text(); throw new Error(body || `Request failed (${response.status})`); } return response.json(); }
  async function load(id: string) {
    try {
      const [projectData, transcriptData, shortData, chapterData, packageData] = await Promise.all([request(`/api/projects/${id}`), request(`/api/projects/${id}/transcript`), request(`/api/projects/${id}/shorts`), request(`/api/projects/${id}/chapters`), request(`/api/projects/${id}/content-package`)]);
      setProject(projectData); setTranscript(transcriptData); setShorts(shortData); setChapters(chapterData); setContentPackage(packageData);
    } catch (value) { setError(errorMessage(value)); }
  }
  const loadProject = useEffectEvent((id: string) => load(id));
  useEffect(() => { params.then(({ projectId: id }) => { setProjectId(id); void loadProject(id); }); }, [params]);
  const projectProcessing = project ? ["queued", "processing"].includes(project.status) : false;
  useEffect(() => { if (!projectId || !projectProcessing) return; const timer = window.setInterval(() => { void request(`/api/projects/${projectId}/status`).then((status) => setProject((current) => current ? { ...current, status: status.status, processing_progress: status.progress, processing_step: status.step, error_message: status.error_message } : current)); }, 4000); return () => window.clearInterval(timer); }, [projectId, projectProcessing]);
  useEffect(() => { if (!projectId || !shorts.some((short) => short.status === "queued" || short.status === "processing")) return; const timer = window.setInterval(() => { void request(`/api/projects/${projectId}/shorts`).then(setShorts); }, 3000); return () => window.clearInterval(timer); }, [projectId, shorts]);

  async function action(name: string, path: string, method = "POST") { setBusy(name); setError(""); try { const data = await request(path, { method }); if (name === "captions") setCaption(data); if (name === "chapters") setChapters(data); if (name === "package") setContentPackage(data); if (name === "shorts") setShorts(data.shorts || []); } catch (value) { setError(errorMessage(value)); } finally { setBusy(""); } }
  async function generateThumbnail() { setThumbnailBusy(true); setThumbnailError(""); try { const data = await request(`/api/projects/${projectId}/thumbnail`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt: thumbnailPrompt }) }); setThumbnailUrl(`${API}${data.media_url}`); } catch (value) { setThumbnailError(thumbnailErrorMessage(value)); } finally { setThumbnailBusy(false); } }
  function generateFromProject() { setThumbnailPrompt(`Create a professional YouTube thumbnail for ${project?.name || "this project"}.`); }

  if (!project) return <main className="min-h-screen bg-[#08090c] p-8 text-zinc-300">{error ? <p className="text-red-300">{error}</p> : <Loader2 className="animate-spin" />}</main>;
  const videoUrl = `${API}/api/projects/${project.id}/video`;
  return <main className="min-h-screen bg-[#08090c] px-4 py-6 text-white sm:px-8">
    <div className="mx-auto max-w-6xl">
      <Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to workspace</Link>
      <header className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-zinc-500">Project detail</p><h1 className="mt-2 text-3xl font-semibold">{project.name}</h1><p className="mt-2 text-sm text-zinc-400">{project.original_filename || project.source_url || "Local project"}</p></div><span className="rounded-full border border-white/10 px-3 py-1 text-sm text-zinc-300">{project.status}</span></header>
      {error && <div className="mb-6 rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}
      <section className="mb-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]">
        <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><video controls className="aspect-video w-full bg-black" src={videoUrl} poster={`${API}/api/projects/${project.id}/thumbnail`} /><div className="grid grid-cols-3 gap-4 p-5 text-sm"><div><span className="block text-zinc-500">Duration</span>{time(project.duration || 0)}</div><div><span className="block text-zinc-500">Resolution</span>{project.width && project.height ? `${project.width} x ${project.height}` : "Not analyzed"}</div><div><span className="block text-zinc-500">Source</span>{project.source_type}</div></div></div>
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Processing</h2><span className="text-sm text-zinc-400">{project.processing_progress || 0}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-emerald-400 transition-all" style={{ width: `${project.processing_progress || 0}%` }} /></div><p className="mt-4 text-sm text-zinc-400">{project.processing_step || "Waiting"}</p>{project.error_message && <p className="mt-4 text-sm text-red-300">{project.error_message}</p>}<div className="mt-6 flex flex-wrap gap-2"><a className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm hover:bg-white/10" href={`${API}/api/projects/${project.id}/thumbnail`} download><Download className="h-4 w-4" /> Thumbnail</a>{project.audio_path && <a className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm hover:bg-white/10" href={`${API}/api/projects/${project.id}/audio`} download><Download className="h-4 w-4" /> Audio</a>}</div></div>
      </section>
      <div className="grid gap-6 lg:grid-cols-2">
        <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><FileText className="h-4 w-4" /> Transcript</h2><span className="text-xs text-zinc-500">{transcript?.status || "missing"}</span></div>{transcript?.segments?.length ? <div className="max-h-80 space-y-3 overflow-auto">{transcript.segments.map((segment, index) => <div key={`${segment.start}-${index}`} className="border-l border-emerald-400/40 pl-3"><span className="text-xs text-emerald-300">{time(segment.start)}</span><p className="text-sm text-zinc-300">{segment.text}</p></div>)}</div> : <p className="text-sm text-zinc-500">No speech segments detected. Generate a transcript with speech before creating captions.</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={() => action("captions", `/api/projects/${project.id}/captions`)} disabled={!!busy || !transcript?.segments?.length} className="inline-flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-sm font-medium text-black disabled:opacity-40"><Captions className="h-4 w-4" />{busy === "captions" ? "Generating..." : "Generate Captions"}</button>{caption && <><a href={`${API}${caption.srt}`} download className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm hover:bg-white/10"><Download className="h-4 w-4" /> Download SRT</a><a href={`${API}${caption.vtt}`} download className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm hover:bg-white/10"><Download className="h-4 w-4" /> Download VTT</a></>}</div>{caption && <p className="mt-3 text-xs text-emerald-300">{caption.segment_count} caption segments ready ({caption.language}).</p>}</section>
        <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4" /> AI Thumbnail</h2><span className="text-xs text-zinc-500">Actual Gemini image generation</span></div>{thumbnailUrl ? <img src={thumbnailUrl} alt="Generated project thumbnail" className="aspect-video w-full rounded-xl object-cover" /> : <div className="flex aspect-video items-center justify-center rounded-xl border border-dashed border-white/15 text-sm text-zinc-500">Your generated thumbnail will appear here.</div>}<textarea value={thumbnailPrompt} onChange={(event) => setThumbnailPrompt(event.target.value)} maxLength={1000} placeholder="Describe the YouTube thumbnail you want..." className="mt-4 min-h-24 w-full resize-none rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none placeholder:text-zinc-600" /><div className="mt-3 flex flex-wrap gap-2"><button onClick={generateFromProject} disabled={thumbnailBusy} className="rounded-lg border border-white/10 px-3 py-2 text-sm hover:bg-white/10">Generate from Project</button><button onClick={() => void generateThumbnail()} disabled={thumbnailBusy || !thumbnailPrompt.trim()} className="inline-flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-sm font-medium text-black disabled:opacity-40">{thumbnailBusy ? <Loader2 className="h-4 w-4 animate-spin" /> : thumbnailUrl ? <RefreshCw className="h-4 w-4" /> : <Sparkles className="h-4 w-4" />}{thumbnailBusy ? "Generating thumbnail..." : thumbnailUrl ? "Generate Again" : "Generate Thumbnail"}</button></div>{thumbnailError && <p className="mt-3 text-sm text-red-300">{thumbnailError}</p>}{thumbnailUrl && <a href={thumbnailUrl} download="nyxarclip-thumbnail.png" className="mt-3 inline-flex items-center gap-2 text-sm text-zinc-300 hover:text-white"><Download className="h-4 w-4" /> Download Thumbnail</a>}</section>
        <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><ScissorsIcon /> Shorts</h2><button onClick={() => action("shorts", `/api/projects/${project.id}/shorts`, "POST")} disabled={!!busy || !project.video_file_path} className="rounded-lg bg-white px-3 py-2 text-sm font-medium text-black disabled:opacity-40">{busy === "shorts" ? "Rendering..." : "Generate Shorts"}</button></div>{shorts.length ? <div className="space-y-3">{shorts.map((short) => <div key={short.id} className="rounded-xl border border-white/10 p-3"><div className="flex justify-between gap-3"><div><p className="text-sm font-medium">{short.title}</p><p className="mt-1 text-xs text-zinc-500">{time(short.start)} · {time(short.duration)} · {short.status}</p><p className="mt-2 text-sm text-zinc-400">{short.hook}</p></div>{short.video_url && <a href={`${API}${short.video_url}`} download className="self-start text-zinc-300 hover:text-white"><Download className="h-4 w-4" /></a>}</div>{short.video_url && <video controls className="mt-3 aspect-[9/16] max-h-64 rounded-lg bg-black" src={`${API}${short.video_url}`} />}</div>)}</div> : <p className="text-sm text-zinc-500">No Shorts generated yet. Candidates are derived from transcript timing.</p>}</section>
        <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><BookOpen className="h-4 w-4" /> Chapters</h2><button onClick={() => action("chapters", `/api/projects/${project.id}/chapters`)} disabled={!!busy || !transcript?.segments?.length} className="rounded-lg border border-white/10 px-3 py-2 text-sm hover:bg-white/10 disabled:opacity-40">{busy === "chapters" ? "Generating..." : "Generate chapters"}</button></div>{chapters.length ? <div className="space-y-2">{chapters.map((chapter) => <div key={chapter.id} className="flex gap-3 text-sm"><span className="font-mono text-emerald-300">{time(chapter.start_time)}</span><span>{chapter.title}</span></div>)}</div> : <p className="text-sm text-zinc-500">No chapters generated yet.</p>}</section>
        <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><Sparkles className="h-4 w-4" /> Content package</h2><button onClick={() => action("package", `/api/projects/${project.id}/content-package`)} disabled={!!busy || !transcript?.text} className="rounded-lg border border-white/10 px-3 py-2 text-sm hover:bg-white/10 disabled:opacity-40">{busy === "package" ? "Generating..." : "Generate with LLM"}</button></div>{contentPackage ? <><p className="text-sm text-zinc-300">{contentPackage.description}</p><div className="mt-4 flex flex-wrap gap-2">{contentPackage.title_suggestions?.map((title) => <span key={title} className="rounded-full bg-white/10 px-3 py-1 text-xs">{title}</span>)}</div></> : <p className="text-sm text-zinc-500">LLM generation is optional and requires OPENAI_API_KEY.</p>}</section>
      </div>
    </div>
  </main>;
}
function ScissorsIcon() { return <Video className="h-4 w-4" />; }
